from playwright.sync_api import Page, expect, sync_playwright

def test_export_modal(page: Page):
    # 1. Arrange: Go to the app.
    page.goto("http://localhost:3000")

    # 2. Act: Navigate to Data Lake
    # The sidebar buttons contain the text 'Data Lake'
    page.get_by_role("button", name="Data Lake").click()

    # 3. Act: Click 'Export Data'
    # This button is inside the Data Lake component
    page.get_by_role("button", name="Export Data").click()

    # 4. Assert: Modal is visible
    expect(page.get_by_role("heading", name="Export Data Lake")).to_be_visible()

    # 5. Assert: Checkboxes are visible (e.g. 'Mesa', 'Strategic Intent')
    # These labels are generated by the loop I modified.
    # Note: The labels are capitalized in UI: col.replace('_', ' ')
    expect(page.get_by_label("Mesa")).to_be_visible()
    expect(page.get_by_label("Strategic intent")).to_be_visible()

    # Check if a checkbox is checked (default state)
    expect(page.get_by_label("Mesa")).to_be_checked()

    # 6. Screenshot
    page.screenshot(path="verification/verification.png")

if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        try:
            test_export_modal(page)
        finally:
            browser.close()
